### ISSUE TITLE
Problem converting aln data to Tmscore

### ISSUE THREAD

**Issue by donal1** [steineggerlab/foldseek#11]
## Expected Behavior

Using this code  foldseek aln2tmscore converted_full/ converted_full/ aln tmscore I should receive tm scores.  

## Current Behavior

I get this error, 
Input database "converted_full/" has the wrong type (Generic)
Allowed input:
- Unknown

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

run foldseek easy-search, then run the above code. 

## Spacepharer Output (for bugs)
Please make sure to also post the complete output of Spacepharer. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute foldseek without any parameters):
* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by martin-steinegger** [comment]
this should be fixed now. See issue https://github.com/steineggerlab/foldseek/issues/13

**Comment by IkramMHD** [comment]
Hello, first of all thank's, Howeever i still have that same issue 

```
MMseqs Version: 1.3c64211
Threads         40
Compressed      0
Verbosity       3

Input database "DatabaseFoldseek24-02/TargetDB" has the wrong type (Aminoacid)
Allowed input:
- Unknown
```
The foldseek i'm using is using conda instalation, is there anyway to make it work. Thank's
